### ISSUE TITLE
コントラクト側の実装変更に伴って、フォームと詳細ページのいくつかの点を修正

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/henkaku-ticket-frontend-old#5]

**Comment by imaichiyyy** [comment]
@yu23ki14 
すみません、いくつか質問させてください。

### hooks/useTicketContract.ts
#### useRegisterTicket関数内
```
usePrepareTicketContractWrite('registerTicket' 〜
```
で渡す引数ですが、
`price, open_blockTimeStamp, close_clockTimeStamp, poolWallet`
を追加する認識で合ってますでしょうか？
また `poolWallet` に入るウォレットアドレスですが、何を入れれば良いでしょうか？

###  components/CreateTicket/Form.tsx
#### HENKAKUトークン所持のチェックについて
以下認識が合っているか教えてください。
- チケットを登録する時にHENKAKUトークンのチェックがcontract側で行われる
- HENKAKUトークンを持っていない場合、frontend側では txWithContract関数内の `writeAsync`関数がエラーを出す

**Comment by yu23ki14** [comment]
> price, open_blockTimeStamp, close_clockTimeStamp, poolWallet

maxSupply, metaDataURL, price, open_blockTimestamp, close_blockTimestamp, poolWallet これらですね
poolWalletはフォームから主催者に入力してもらいます！

**Comment by yu23ki14** [comment]
> 以下認識が合っているか
合っております！

**Comment by imaichiyyy** [comment]
@yu23ki14 
ありがとうございます！
ちなみに現状 `usePrepareTicketContractWrite('registerTicket' 〜` に `poolWallet` を渡す必要があるのですが、
現状どのアドレス（ダミー？）を入れれば良いでしょうか。。？

**Comment by yu23ki14** [comment]
imaichiyyyさんのテストアドレスで大丈夫ですよ！
こちらは本当に自由なので

**Comment by imaichiyyy** [comment]
ありがとうございます！
とりあえずいくつかアドレスを入れてみたのですが、
```
underflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-underflow ] (fault="underflow", operation="BigNumber.from", value=1679379382.418, code=NUMERIC_FAULT, version=bignumber/5.7.0)
```
というエラーが発生しまして…こちらって何かわかりますでしょうか。。？

**Comment by imaichiyyy** [comment]
あ、すみません。
上記エラーではなく、こちらでした。。
```
Error: invalid address or ENS name (argument="name", value={"gasLimit":{"type":"BigNumber","hex":"0x10c8e0"}}, code=INVALID_ARGUMENT, version=contracts/5.7.0)
```

**Comment by imaichiyyy** [comment]
すみません、エラー自己解決しました。。！
