### ISSUE TITLE
変数名の中からNengajo -> Ticketへ変更する

### ISSUE THREAD

**Issue by imaichiyyy** [henkaku-center/henkaku-ticket-frontend-old#7]

**Comment by imaichiyyy** [comment]
@yu23ki14 
すみません、先程ご対応いただいた abi や typesディレクトリに入っている設定ファイルのmigrationですが、
数点質問させてください。

- `/abi/Nengajo.json` と `/abi/PublicNengajo.json` って必要ですか？不要なら削除って可能でしょうか。。？
- typesディレクトリ内の `public` という変数名が厳格モードだと予約後に該当するため、ビルドエラーが発生しています。可能であれば名前を変更いただくか、もしくは厳格モードを解除するかになると思いますがどちらが良いでしょうか？

**Comment by yu23ki14** [comment]
> /abi/Nengajo.json と /abi/PublicNengajo.json

消して大丈夫です！

> public という変数名が厳格モードだと予約後に該当するため

publicってどこでつかっているやつですかね？

**Comment by imaichiyyy** [comment]
> 消して大丈夫です！

了解です！
ちなみにabi配下のファイルってこちらで手動削除しても大丈夫ですか？

> publicってどこでつかっているやつですかね？  

`/types/factories/contracts/public` をインポートする際に出てきます。  
`/types/contracts/index.ts` や `/types/factories/contracts/index.ts` などに記載があります！

**Comment by yu23ki14** [comment]
> 手動で削除
OKです！

> public
それらのファイルつかっておらず、今後もcommunity配下しか使わないと思うのでファイル消しちゃってください！

**Comment by imaichiyyy** [comment]
了解です、ありがとうございます！
